### ISSUE TITLE
CI is a little flaky, needs resiliency added to network activity

### ISSUE THREAD

**Issue by mikehardy** [thebergamo/react-native-fbsdk-next#102]
## 🐛 Bug Report

CI fails sometimes, and it is not the module's fault.

Specifically sometimes yarn fails to install packages, though I imagine we will see Pod install failures in the future as well.

## To Reproduce

Run CI a few times, and examine the results.

## Expected Behavior

CI does not fail on transient network failures

## Code Example

A typical solution would be to add https://github.com/nick-invision/retry/ to the workflows, as in other repos.

An example:

https://github.com/invertase/react-native-firebase/blob/47d226526fec4dcee6edc5f5c2e37f430e91cae9/.github/workflows/tests_e2e_ios.yml#L78-L84

```yaml
      - name: Yarn Install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --no-audit --prefer-offline
```

## Environment

Github actions runner
